### ISSUE TITLE
Is this project still active？

### ISSUE THREAD

**Issue by wrhsd1** [nathanrchn/perplexityai#2]
Is this project still active? I encountered an error while running it and couldn't retrieve the answers correctly. 
Traceback (most recent call last):
  File "/root/perplexityai/1.py", line 5, in <module>
    perplexity = Perplexity()
  File "/root/perplexityai/Perplexity.py", line 23, in __init__
    self.sid: str = self.get_sid()
  File "/root/perplexityai/Perplexity.py", line 47, in get_sid
    response = loads(self.session.get(
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Thank you

**Comment by binarycraft007** [comment]
https://github.com/binarycraft007/perplexity
For alternative, this is a golang perplexity sdk based on reverse engineered android protocol, which is working.

**Comment by nathanrchn** [comment]
Sorry for the delay. The error is now corrected. It works now.

**Comment by gtroisi** [comment]
@nathanrchn unluckily still having this issue, even with the latest  version on a Mac.

Traceback (most recent call last):
  File "/Users/gabriele/perplexityai-main/main.py", line 3, in <module>
    perplexity = Perplexity()
  File "/Users/gabriele/perplexityai-main/Perplexity.py", line 24, in __init__
    self.sid: str = self.get_sid()
  File "/Users/gabriele/perplexityai-main/Perplexity.py", line 49, in get_sid
    response = loads(self.session.get(
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/gabriele/miniforge3/envs/perplexity/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by nathanrchn** [comment]
Yes, they have updated the cloudfare settings so i change the User-Agent to bypass this. Now it should works. Tell me if it's not the case.
